config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('fidbeck/', include('fidbeck.urls', namespace='fidbeck')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fidbeck/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from fidbeck.apps import FidbeckConfig

from fidbeck.views import Fidbeckcreateview, FidbecklistView, Fidbecdetaileview, Fidbecupdateview, FidbecdeleteView



app_name = FidbeckConfig.name



urlpatterns = [
    path('create/', Fidbeckcreateview.as_view(), name='create'),
    path('', FidbecklistView.as_view(), name='list'),
    path('view/<int:pk>/<slug:slug>', Fidbecdetaileview.as_view(), name='view'),
    path('edit/<int:pk>/<slug:slug>', Fidbecupdateview.as_view(), name='edit'),
    path('delete/<int:pk>/<slug:slug>', FidbecdeleteView.as_view(), name='delete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig

from users.views import LoginView, LogoutView, RegisterView, verify_email
# EmailVerify

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', verify_email, name='verify'),
    # path('activate/<str:token>/', activate_user, name='activate_user'),
    # path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email'), name='confirm_email'),
    # path('verify_email/<uidb64>/<token>', EmailVerify.as_view(), name='verify_emaile')
]

fidbeck/models.py
from django.db import models



class Fidbeck(models.Model):
    title = models.CharField(max_length=100, verbose_name='название', unique=True)
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.TextField(verbose_name='содержимое', unique=True)
    preview = models.ImageField(upload_to='product_images', blank=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)


    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True)

fidbeck/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from fidbeck.models import Fidbeck


class Fidbeckcreateview(CreateView):
    model = Fidbeck
    fields = ['title', 'content', 'preview']
    success_url = reverse_lazy('fidbeck:list')


    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)




class FidbecklistView(ListView):
    model = Fidbeck

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class Fidbecdetaileview(DetailView):
    model = Fidbeck

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object



class Fidbecupdateview(UpdateView):
        model = Fidbeck
        fields = ['title', 'content', 'preview']

        def get_success_url(self):
            return reverse('fidbeck:view', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


class FidbecdeleteView(DeleteView):
    model = Fidbeck
    success_url = reverse_lazy('fidbeck:list')

fidbeck/templates/fidbeck/fidbeck_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
     <div class="row text-center">
         <div class = 'col-18'>
             <div class = 'card'>
                 <div class = 'card-body'>
                     <form method="post">
                         {% csrf_token %}
                         <p>Хотите удалить отзыв "{{object.title}}"?</p>
                         <button type="submit" class="btn-success">Подтвердить</button>
                     </form>
                 </div>
             </div>
         </div>

     </div>
{% endblock %}

fidbeck/templates/fidbeck/fidbeck_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="container">
    <div class="row text-center">

        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">

                    <h4 class="my-0 font-weight-normal">{{ object.title }} ({{ object.slug }})</h4>

        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>

                </div>
                <div class="card-body">
                    <img src='{{ object.preview|mymedia }}' alt="Здесь должна быть ваша картинка" class="img-fluid" style="width: 150px; height: 100px;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.content }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    <p>Просмотры: {{ object.views_count }}</p>
                </div>
            </div>
        </div>

    </div>
</div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

fidbeck/templates/fidbeck/fidbeck_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
     <div class="row text-center">
         <div class = 'col-18'>
             <div class = 'card'>
                 <div class = 'card-body'>
                     <form method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {{ form.as_p}}
                         <button type="submit" class="btn-success">Создать</button>
                     </form>
                 </div>
             </div>
         </div>

     </div>
{% endblock %}

fidbeck/templates/fidbeck/fidbeck_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Ваши отзывы</h1>
</div>

<div class="container">
    <div class="row text-center">
        {%for object in object_list%}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{ object.title }}</h1>
                   <div class="card-header">
                   <a href="{% url 'fidbeck:view' object.pk object.slug %}" class="btn btn-primary">Перейти к просмотру</a>
                   <a href="{% url 'fidbeck:edit' object.pk object.slug %}" class="btn btn-secondary">Изменить</a>
                      <a href="{% url 'fidbeck:delete' object.pk object.slug %}" class="btn btn-danger">Удалить</a>
                   </div>
                </div>
                <div class="card-body">
                    <img src='{{ object.preview|mymedia }}' alt="Здесь должна быть ваша картинка" class="img-fluid" style="width: 150px; height: 100px;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.content }}</li>
                    </ul>


                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}