catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from catalog.views import Contactlistview, ProductByCategoryListView, Productlistview, ProductCreate, ProductUpdateview

from catalog.apps import CatalogConfig
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', Productlistview.as_view(), name='product_list'),
    path('contacts/', Contactlistview.as_view(), name = 'contact_list'),
    path('good/<int:pk>', cache_page(60)(ProductByCategoryListView.as_view()), name='product_detail'),
    path('create/', ProductCreate.as_view(), name = 'create_product'),
    path('update/<int:pk>/', ProductUpdateview.as_view(), name='update_product'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('fidbeck/', include('fidbeck.urls', namespace='fidbeck')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fidbeck/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from fidbeck.apps import FidbeckConfig

from fidbeck.views import Fidbeckcreateview, FidbecklistView, Fidbecdetaileview, Fidbecupdateview, FidbecdeleteView



app_name = FidbeckConfig.name



urlpatterns = [
    path('create/', Fidbeckcreateview.as_view(), name='create'),
    path('', FidbecklistView.as_view(), name='list'),
    path('view/<int:pk>/<slug:slug>', Fidbecdetaileview.as_view(), name='view'),
    path('edit/<int:pk>/<slug:slug>', Fidbecupdateview.as_view(), name='edit'),
    path('delete/<int:pk>/<slug:slug>', FidbecdeleteView.as_view(), name='delete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig

from users.views import LoginView, LogoutView, RegisterView, verify_email
# EmailVerify

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', verify_email, name='verify'),
    # path('activate/<str:token>/', activate_user, name='activate_user'),
    # path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email'), name='confirm_email'),
    # path('verify_email/<uidb64>/<token>', EmailVerify.as_view(), name='verify_emaile')
]

catalog/models.py
from django.conf import settings
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='название')
    description = models.TextField(verbose_name='описание')

class Product(models.Model):
    ACTIVE_CHOICES = (
        ('yes', 'Активна'),
        ('no', 'Не активна'),
    )
    name = models.CharField(max_length=100, verbose_name='название')  # наименование
    description = models.TextField(verbose_name='описание')  # описание
    image = models.ImageField(upload_to='product_images', blank=True, null=True)  # изображение (превью)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена')  # цена за покупку
    created_date = models.DateTimeField(auto_now_add=True)  # дата создания
    last_modified_date = models.DateTimeField(auto_now=True)  # дата последнего изменения
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, verbose_name='пользователь')
    is_published = models.CharField(default=False, choices=ACTIVE_CHOICES, verbose_name='опубликовано')

    class Meta:
        verbose_name = 'Расслыка'

        permissions = [
            ('can_change_product', 'Can_change_product'),
        ]


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=20, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='имя версии')
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.version_name

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    FORBIDDEN = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    def form_valid(self, form):
        form.instance.user = self.request.user  # привязываем текущего пользователя к полю user
        return super().form_valid(form)

    def clean_name(self):
        name = self.cleaned_data.get('name')

        for word in self.FORBIDDEN:
            if word.lower() in name.lower():
                raise forms.ValidationError('Запрещенное слово: {}'.format(word))
        return name


    class Meta:
        model = Product
        fields = ["name", "description", "image", "category", "purchase_price", "is_published"]



class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['product', 'version_number', 'version_name', 'is_active']


class ModeratorProductForm(ProductForm):
    class Meta:
        model = Product
        fields = ['description', 'category', 'is_published']

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from catalog.models import Product, Version, Category
from pytils.translit import slugify
from catalog.services import get_category_cache
from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from rest_framework.permissions import BasePermission

from rest_framework.exceptions import PermissionDenied




# class IsEnrolled(BasePermission):
#     def has_object_permission(self, request, view, obj):
#         return obj.user == request.user



class Productlistview(ListView):
    model = Product
    template_name = 'catalog/home.html'


class Contactlistview(ListView):
    model = Product
    template_name = 'catalog/contacts.html'


class ProductByCategoryListView(DetailView):
    model = Product
    template_name = 'catalog/good_detail.html'

# @login_required
class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        name = form.cleaned_data.get('name')
        description = form.cleaned_data.get('description')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']

        for word in forbidden_words:
            if word in name.lower() or word in description.lower():
                form.add_error(None, f"Запрещенное слово '{word}' найдено в названии или описании продукта.")
                return self.form_invalid(form)

        # Устанавливаем текущего пользователя как владельца продукта
        form.instance.user = self.request.user

        return super().form_valid(form)


# @login_required
class Http401:
    pass


class ProductUpdateview(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    permission_required = 'product.can_change_desc_permission'
    def get_form_class(self):
        if self.request.user.is_staff:
            return ModeratorProductForm
        return ProductForm

    def has_permission(self):
        obj = self.get_object()
        if self.request.user == obj.user or self.request.user.is_staff:
            return True
        return super().has_permission()


    # def dispatch(self, request, *args, **kwargs):
    #     obj = self.get_object()
    #     if obj.user != self.request.user and not (self.request.user.is_superuser or self.request.user.is_staff):
    #         raise Http401("У вас нет прав для редактирования этого продукта")
    #     return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        form.instance.user = self.request.user


        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            self.object.email = self.request.user
            formset.save()


        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        context_data['formset'] = VersionFormSet
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormSet(instance=self.object)

        return context_data

    def your_view(request):
        registered_by = request.user.email

        return registered_by


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        if settings.CACHE_ENABLED:
            category_list = get_category_cache()
            return category_list
        return super().get_queryset()

catalog/templates/catalog/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Catalog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'fidbeck:list' %}">Ваши отзывы</a>
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
            {% else %}
                 <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
                 <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
    </nav>
            </form>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
     <div class="row text-center">
         <div class = 'col-18'>
             <div class = 'card'>
                 <div class = 'card-body'>
                     <form method="post">
                         {% csrf_token %}
                         {{ form.as_p}}
                         <button type="submit" class="btn-success">Создать</button>
                     </form>
                 </div>
             </div>
         </div>

     </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/good.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="container">
    <div class="row text-center">

        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object_list.name }}</h4>
                </div>
                <div class="card-body">
                     <img src='{{ object_list.image|mymedia }}' alt="продукты" class="img-fluid">
                    <h1 class="card-title pricing-card-title">{{ object_list.purchase_price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object_list.description }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>

    </div>
</div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/good_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="container">
    <div class="row text-center">

        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object_list.name }}</h4>
                </div>
                <div class="card-body">
                     <img src='{{ object_list.image|mymedia }}' alt="продукты" class="img-fluid">
                    <h1 class="card-title pricing-card-title">{{ object_list.purchase_price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object_list.description }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>

    </div>
</div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Садовод</h1>
    <p class="lead">Садовод - это отличный магазин для покупки овощей, фруктов, ягод</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        </div>
        {%for object in object_list%}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img src='{{ object.image|mymedia }}' alt="продукты" class="img-fluid" style="width: 150px; height: 100px;">
                    <h1 class="card-title pricing-card-title">{{ object.purchase_price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description|slice:":30" }}</li>
                         {% if request.user.is_authenticated %}
                         <span class="text-muted">Зарегистрирован: {{ object.user.email }}</span>
                         {% endif %}
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary" onclick="location.href='/good/{{ object.id }}'">Подробнее</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary" onclick="location.href=&quot;{% url 'fidbeck:create' %}&quot;">Оставить отзыв</button>
                     <a href="{% url 'catalog:update_product' object.pk %}" type="button" class="btn btn-primary">Обновить</a>
                      <li>- {{ object.is_published }}</li>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">

         <div class="row text-center">
             <div class="col-6">
                <div class="card h-100">
                     <div class="card-body">
                             {% csrf_token %}
                             {{ form.as_p }}
                             <button type="submit" class="btn-success">Создать</button>
                     </div>
                 </div>
             </div>
             <div class="col-6">
                  <div class="card h-100">
                      <h3 class="card-title">
                          Версия продукта
                      </h3>
                     <div class="card-body">

                         {{ formset.management_form }}

                         {% for form in formset.forms %}
                             {{ form.as_p }}
                         {% endfor %}

                     </div>
                 </div>
             </div>

         </div>
    </form>
</div>
{% endblock %}